### ISSUE TITLE
程序流程

### ISSUE THREAD

**Issue by shenshengke701** [xiaobaicxy/Operator_QA_Based_KB#2]
您好 很感谢您分析的代码，我按照您的文件训练好了，测试部分是在哪块呢 ？看了前面的代码流程，还没看完是否可以告知一下呢？感谢感谢

**Comment by xiaobaicxy** [comment]
> 您好 很感谢您分析的代码，我按照您的文件训练好了，测试部分是在哪块呢 ？看了前面的代码流程，还没看完是否可以告知一下呢？感谢感谢

您好，直接bash run.sh一键就能跑出最终结果，最终结果在./results/final_results/result.csv中，因为测试集没有label，所以测不了性能，只能把./results/final_results/kbqa_results.json文件提交到官网在线测试性能。
